#  ———————————————————————————————————————————————————————————————————————————
#  Tell Homebrew what to do when we run `brew bundle`
#  ———————————————————————————————————————————————————————————————————————————

# For yabai, skhd, borders
tap "FelixKratz/formulae"
tap "koekeishiya/formulae"

# CLI tools
brew "gh"
brew "ffmpeg"
brew "node"
brew "python@3.13"
brew "rust"
brew "wget"
brew "go"
brew "openjdk"
brew "bat"
brew "pnpm"
brew "jq"
brew "lazygit"
brew "just"
brew "starship"
brew "tmux"
brew "tree"
brew "mosh"
brew "docker"
brew "docker-completion"
brew "spicetify-cli"
brew "spotify_player"
brew "yabai"
brew "koekeishiya/formulae/skhd"
brew "fzf"
brew "screenresolution"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
brew "yt-dlp"
brew "neovim"
brew "yazi"
brew "btop"
brew "bookokrat"
brew "aerc"
brew "weechat"
brew "zoxide"
# hass-cli: pip install homeassistant-cli

# Necessities 
cask "iterm2"
cask "ghostty"
cask "firefox@nightly"
cask "visual-studio-code"
cask "parsec"
cask "mullvad-vpn"
#cask "mtmr"
#cask "halloy"     # replaced by weechat
#cask "google-chrome"
cask "qbittorrent"
cask "fx-cast-bridge"
cask "wine-stable"
#cask "obsidian"   # replaced by neovim + obsidian.nvim
cask "home-assistant"
cask "appcleaner"

# Audio/video
cask "audio-hijack"
cask "loopback"
cask "handbrake-app" 
#cask "obs"
cask "vlc"
cask "stolendata-mpv"
#cask "spotify"    # replaced by spotify_player

# Entertainment
#cask "discord"    # install discordo via: go install github.com/ayn2op/discordo@latest
cask "steam"
cask "virtualdj"
cask "crossover"
